name: care_bridge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2  # Compatible core for Auth + Firestore
  firebase_auth: ^5.7.0   # Email/password + displayName
  cloud_firestore: ^5.4.3 # For storing/fetching ASHA ID, roles, etc.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
