// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqiSxqYQK_9BYZaN91F25Nzu9_DxgkM5Y',
    appId: '1:527008735811:web:8ee64733131a3b649daaf6',
    messagingSenderId: '527008735811',
    projectId: 'care-bridge-65cf3',
    authDomain: 'care-bridge-65cf3.firebaseapp.com',
    storageBucket: 'care-bridge-65cf3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7X8G65d2UPmRrF7gHNAsEWndtT1i103Y',
    appId: '1:527008735811:android:f162530c1850905a9daaf6',
    messagingSenderId: '527008735811',
    projectId: 'care-bridge-65cf3',
    storageBucket: 'care-bridge-65cf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEdanp1uktiqKo721c3uOzJyxS5TBm0Tk',
    appId: '1:527008735811:ios:21d41a4fa5b829059daaf6',
    messagingSenderId: '527008735811',
    projectId: 'care-bridge-65cf3',
    storageBucket: 'care-bridge-65cf3.firebasestorage.app',
    iosBundleId: 'com.example.careBridge',
  );
}
