import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';  // For persistence settings
import 'firebase_options.dart';  // Generated by 'flutterfire configure'
import 'login_view.dart';  // Your LoginView (ASHA ID login)
import 'register_view.dart';  // Register page
import 'homepage.dart';  // Fixed HomePage

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // Enable offline persistence (caches queries for ASHA low-connectivity)
  FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true,
    cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,  // Dev: Unlimited; Prod: 100 * 1024 * 1024 (100MB)
  );
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ASHA Vaccine Tracker',
      theme: ThemeData(
        primarySwatch: Colors.green,  // Matches your app's primary color (0xFFA8FBD3)
        useMaterial3: true,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      initialRoute: '/login',  // Starts on your LoginView
      routes: {
        '/login': (context) => const LoginView(),  // Your ASHA ID login page
        '/home': (context) => const HomePage(),  // Dashboard
        '/register': (context) => const RegisterPage(),  // Register page
      },
      debugShowCheckedModeBanner: false,
    );
  }
}
